In [2]:
import pandas as pd
import numpy as np

#FIRST DATASET

In [7]:
data =pd.read_csv("/Data-cleaning-for-beginners-using-pandas.csv")
data

    Index   Age      Salary  Rating       Location  Established Easy Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3  64.0   $44k-$99k     4.4       India In         1988         -1
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009         -1
12     12   NaN   $44k-$99k     0.0       India,In         1999         -1
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16     16  19.0   $19k-$40k     4.5       India,In         1984         -1
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22     22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0   $44k-$99k     5.4       India,In         1935         -1
28     28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1

#AGE COLUMN

In [8]:
avg_age=data['Age'].mean()
data['Age']=data.Age.fillna(avg_age)
data['Age']=data.Age.round(decimals=1)

In [9]:
data['Age']=data['Age'].astype('int64')
data

    Index  Age      Salary  Rating       Location  Established Easy Apply
0       0   44   $44k-$99k     5.4       India,In         1999       TRUE
1       1   66   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   39   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3   64   $44k-$99k     4.4       India In         1988         -1
4       4   25   $44k-$99k     6.4  Australia Aus         2002         -1
5       5   44   $77k-$89k     1.4       India,In         1999       TRUE
6       6   21   $44k-$99k     0.0    New York,Ny           -1         -1
7       7   44   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8   35   $44k-$99k     5.4    New York,Ny           -1         -1
9       9   22   $44k-$99k     7.7       India,In           -1       TRUE
10     10   55   $10k-$49k     5.4       India,In         2008       TRUE
11     11   44   $10k-$49k     6.7       India,In         2009         -1
12     12   39   $44k-$99k     0.0       India,In         1999         -1
13     13   25   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14   66   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15   44  $88k-$101k     3.0  Australia Aus         1999         -1
16     16   19   $19k-$40k     4.5       India,In         1984         -1
17     17   39   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18   35   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19   32   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   39   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21   35   $44k-$99k     5.0    New York,Ny         1946         -1
22     22   19   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   39   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24   13   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25   55   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   39   $55k-$66k     NaN       India,In         1934       TRUE
27     27   52   $44k-$99k     5.4       India,In         1935         -1
28     28   39   $39k-$88k     3.4  Australia Aus         1932         -1

#SALARY COLUMN

In [10]:
data['Salary']=data['Salary'].str.replace("$"," ")
data['Salary']=data['Salary'].str.replace("k","000")
data

<ipython-input-10-961fc3738054>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Salary']=data['Salary'].str.replace("$"," ")

    Index  Age          Salary  Rating       Location  Established Easy Apply
0       0   44    44000- 99000     5.4       India,In         1999       TRUE
1       1   66    55000- 66000     3.5    New York,Ny         2002       TRUE
2       2   39    77000- 89000    -1.0    New York,Ny           -1         -1
3       3   64    44000- 99000     4.4       India In         1988         -1
4       4   25    44000- 99000     6.4  Australia Aus         2002         -1
5       5   44    77000- 89000     1.4       India,In         1999       TRUE
6       6   21    44000- 99000     0.0    New York,Ny           -1         -1
7       7   44    44000- 99000    -1.0  Australia Aus           -1         -1
8       8   35    44000- 99000     5.4    New York,Ny           -1         -1
9       9   22    44000- 99000     7.7       India,In           -1       TRUE
10     10   55    10000- 49000     5.4       India,In         2008       TRUE
11     11   44    10000- 49000     6.7       India,In         2009         -1
12     12   39    44000- 99000     0.0       India,In         1999         -1
13     13   25    44000- 99000    -1.0  Australia Aus         2019       TRUE
14     14   66    44000- 99000     4.0  Australia Aus         2020       TRUE
15     15   44   88000- 101000     3.0  Australia Aus         1999         -1
16     16   19    19000- 40000     4.5       India,In         1984         -1
17     17   39    44000- 99000     5.3    New York,Ny         1943       TRUE
18     18   35    44000- 99000     6.7    New York,Ny         1954       TRUE
19     19   32    44000- 99000     3.3    New York,Ny         1955       TRUE
20     20   39    44000- 99000     5.7    New York,Ny         1944       TRUE
21     21   35    44000- 99000     5.0    New York,Ny         1946         -1
22     22   19    55000- 66000     7.8    New York,Ny         1988       TRUE
23     23   39    44000- 99000     2.4    New York,Ny         1999       TRUE
24     24   13    44000- 99000    -1.0    New York,Ny         1987         -1
25     25   55    44000- 99000     0.0  Australia Aus         1980       TRUE
26     26   39    55000- 66000     NaN       India,In         1934       TRUE
27     27   52    44000- 99000     5.4       India,In         1935         -1
28     28   39    39000- 88000     3.4  Australia Aus         1932         -1

#RATING COLUMN

In [11]:
avg_rating=data['Rating'].mean()
data['Rating']=data['Rating'].fillna(avg_rating)
data['Rating']=data.Rating.round(decimals=1)
data

    Index  Age          Salary  Rating       Location  Established Easy Apply
0       0   44    44000- 99000     5.4       India,In         1999       TRUE
1       1   66    55000- 66000     3.5    New York,Ny         2002       TRUE
2       2   39    77000- 89000    -1.0    New York,Ny           -1         -1
3       3   64    44000- 99000     4.4       India In         1988         -1
4       4   25    44000- 99000     6.4  Australia Aus         2002         -1
5       5   44    77000- 89000     1.4       India,In         1999       TRUE
6       6   21    44000- 99000     0.0    New York,Ny           -1         -1
7       7   44    44000- 99000    -1.0  Australia Aus           -1         -1
8       8   35    44000- 99000     5.4    New York,Ny           -1         -1
9       9   22    44000- 99000     7.7       India,In           -1       TRUE
10     10   55    10000- 49000     5.4       India,In         2008       TRUE
11     11   44    10000- 49000     6.7       India,In         2009         -1
12     12   39    44000- 99000     0.0       India,In         1999         -1
13     13   25    44000- 99000    -1.0  Australia Aus         2019       TRUE
14     14   66    44000- 99000     4.0  Australia Aus         2020       TRUE
15     15   44   88000- 101000     3.0  Australia Aus         1999         -1
16     16   19    19000- 40000     4.5       India,In         1984         -1
17     17   39    44000- 99000     5.3    New York,Ny         1943       TRUE
18     18   35    44000- 99000     6.7    New York,Ny         1954       TRUE
19     19   32    44000- 99000     3.3    New York,Ny         1955       TRUE
20     20   39    44000- 99000     5.7    New York,Ny         1944       TRUE
21     21   35    44000- 99000     5.0    New York,Ny         1946         -1
22     22   19    55000- 66000     7.8    New York,Ny         1988       TRUE
23     23   39    44000- 99000     2.4    New York,Ny         1999       TRUE
24     24   13    44000- 99000    -1.0    New York,Ny         1987         -1
25     25   55    44000- 99000     0.0  Australia Aus         1980       TRUE
26     26   39    55000- 66000     3.5       India,In         1934       TRUE
27     27   52    44000- 99000     5.4       India,In         1935         -1
28     28   39    39000- 88000     3.4  Australia Aus         1932         -1

In [12]:
data['Reading']=data['Rating'].replace(-1,1)
data.head()

,Index,Age,Salary,Rating,Location,Established,Easy Apply,Reading
0,0,44,44000- 99000,5.4,"India,In",1999,TRUE,5.4
1,1,66,55000- 66000,3.5,"New York,Ny",2002,TRUE,3.5
2,2,39,77000- 89000,-1.0,"New York,Ny",-1,-1,1.0
3,3,64,44000- 99000,4.4,India In,1988,-1,4.4
4,4,25,44000- 99000,6.4,Australia Aus,2002,-1,6.4

#LOCATION COLUMN

In [13]:
data['Location']=data['Location'].replace({"India,In": "India","India In":"India","New york,Ny":"New York","Australia Aus":"Australia"})
data.head()

,Index,Age,Salary,Rating,Location,Established,Easy Apply,Reading
0,0,44,44000- 99000,5.4,India,1999,TRUE,5.4
1,1,66,55000- 66000,3.5,"New York,Ny",2002,TRUE,3.5
2,2,39,77000- 89000,-1.0,"New York,Ny",-1,-1,1.0
3,3,64,44000- 99000,4.4,India,1988,-1,4.4
4,4,25,44000- 99000,6.4,Australia,2002,-1,6.4

#ESTABLISHED COLUMN

In [14]:
data['Established']=data['Established'].replace(-1,np.nan)

In [15]:
established =data['Established'].mean()
data['Established']=data['Established'].fillna(established)
data['Established']=data['Established'].round(decimals=1)
data['Established']=data['Established'].astype('int64')
data

,Index,Age,Salary,Rating,Location,Established,Easy Apply,Reading
0,0,44,44000- 99000,5.4,India,1999,TRUE,5.4
1,1,66,55000- 66000,3.5,"New York,Ny",2002,TRUE,3.5
2,2,39,77000- 89000,-1.0,"New York,Ny",1980,-1,1.0
3,3,64,44000- 99000,4.4,India,1988,-1,4.4
4,4,25,44000- 99000,6.4,Australia,2002,-1,6.4
5,5,44,77000- 89000,1.4,India,1999,TRUE,1.4
6,6,21,44000- 99000,0.0,"New York,Ny",1980,-1,0.0
7,7,44,44000- 99000,-1.0,Australia,1980,-1,1.0
8,8,35,44000- 99000,5.4,"New York,Ny",1980,-1,5.4
9,9,22,44000- 99000,7.7,India,1980,TRUE,7.7
10,10,55,10000- 49000,5.4,India,2008,TRUE,5.4
11,11,44,10000- 49000,6.7,India,2009,-1,6.7
12,12,39,44000- 99000,0.0,India,1999,-1,0.0
13,13,25,44000- 99000,-1.0,Australia,2019,TRUE,1.0
14,14,66,44000- 99000,4.0,Australia,2020,TRUE,4.0
15,15,44,88000- 101000,3.0,Australia,1999,-1,3.0
16,16,19,19000- 40000,4.5,India,1984,-1,4.5
17,17,39,44000- 99000,5.3,"New York,Ny",1943,TRUE,5.3
18,18,35,44000- 99000,6.7,"New York,Ny",1954,TRUE,6.7
19,19,32,44000- 99000,3.3,"New York,Ny",1955,TRUE,3.3
20,20,39,44000- 99000,5.7,"New York,Ny",1944,TRUE,5.7
21,21,35,44000- 99000,5.0,"New York,Ny",1946,-1,5.0
22,22,19,55000- 66000,7.8,"New York,Ny",1988,TRUE,7.8
23,23,39,44000- 99000,2.4,"New York,Ny",1999,TRUE,2.4
24,24,13,44000- 99000,-1.0,"New York,Ny",1987,-1,1.0
25,25,55,44000- 99000,0.0,Australia,1980,TRUE,0.0
26,26,39,55000- 66000,3.5,India,1934,TRUE,3.5
27,27,52,44000- 99000,5.4,India,1935,-1,5.4
28,28,39,39000- 88000,3.4,Australia,1932,-1,3.4

#EASY APPLY COLUMN

In [16]:
data['Easy Apply']=data['Easy Apply'].replace("-1","FALSE")
data

,Index,Age,Salary,Rating,Location,Established,Easy Apply,Reading
0,0,44,44000- 99000,5.4,India,1999,TRUE,5.4
1,1,66,55000- 66000,3.5,"New York,Ny",2002,TRUE,3.5
2,2,39,77000- 89000,-1.0,"New York,Ny",1980,FALSE,1.0
3,3,64,44000- 99000,4.4,India,1988,FALSE,4.4
4,4,25,44000- 99000,6.4,Australia,2002,FALSE,6.4
5,5,44,77000- 89000,1.4,India,1999,TRUE,1.4
6,6,21,44000- 99000,0.0,"New York,Ny",1980,FALSE,0.0
7,7,44,44000- 99000,-1.0,Australia,1980,FALSE,1.0
8,8,35,44000- 99000,5.4,"New York,Ny",1980,FALSE,5.4
9,9,22,44000- 99000,7.7,India,1980,TRUE,7.7
10,10,55,10000- 49000,5.4,India,2008,TRUE,5.4
11,11,44,10000- 49000,6.7,India,2009,FALSE,6.7
12,12,39,44000- 99000,0.0,India,1999,FALSE,0.0
13,13,25,44000- 99000,-1.0,Australia,2019,TRUE,1.0
14,14,66,44000- 99000,4.0,Australia,2020,TRUE,4.0
15,15,44,88000- 101000,3.0,Australia,1999,FALSE,3.0
16,16,19,19000- 40000,4.5,India,1984,FALSE,4.5
17,17,39,44000- 99000,5.3,"New York,Ny",1943,TRUE,5.3
18,18,35,44000- 99000,6.7,"New York,Ny",1954,TRUE,6.7
19,19,32,44000- 99000,3.3,"New York,Ny",1955,TRUE,3.3
20,20,39,44000- 99000,5.7,"New York,Ny",1944,TRUE,5.7
21,21,35,44000- 99000,5.0,"New York,Ny",1946,FALSE,5.0
22,22,19,55000- 66000,7.8,"New York,Ny",1988,TRUE,7.8
23,23,39,44000- 99000,2.4,"New York,Ny",1999,TRUE,2.4
24,24,13,44000- 99000,-1.0,"New York,Ny",1987,FALSE,1.0
25,25,55,44000- 99000,0.0,Australia,1980,TRUE,0.0
26,26,39,55000- 66000,3.5,India,1934,TRUE,3.5
27,27,52,44000- 99000,5.4,India,1935,FALSE,5.4
28,28,39,39000- 88000,3.4,Australia,1932,FALSE,3.4

In [17]:
data['Easy Apply']=data['Easy Apply'].astype(bool)

#DATA TYPE

In [18]:
data.dtypes

Index            int64
Age              int64
Salary          object
Rating         float64
Location        object
Established      int64
Easy Apply        bool
Reading        float64
dtype: object

#SECOND DATASET

In [3]:
import numpy as np
import pandas as pd

In [6]:
df =pd.read_csv("/content/chipotle.tsv",sep="\t")
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [26]:
df['choice_description']=df['choice_description'].fillna('none')
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,none,2,2
1,1,1,Izze,Clementine,3,3
2,1,1,Nantucket Nectar,Apple,3,3
3,1,1,Chips and Tomatillo-Green Chili Salsa,none,2,2
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16,32

In [7]:
df.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [8]:
df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [9]:
df['item_price'] = df['item_price'].str.replace('$','')
df['item_price'] = df['item_price'].astype('float64')
df.head(10)

<ipython-input-9-4d5edb54b2d7>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['item_price'] = df['item_price'].str.replace('$','')

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25

In [10]:
df['choice_description']=df['choice_description'].fillna('none')
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,none,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,none,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [11]:
df.isna()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False               False       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False               False       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [12]:
df.isna().sum()

order_id              0
quantity              0
item_name             0
choice_description    0
item_price            0
dtype: int64

In [13]:
df['item_price']=df['item_price'].replace('$','')
df['item_price']=df['item_price'].astype(int)
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,none,2
1,1,1,Izze,[Clementine],3
2,1,1,Nantucket Nectar,[Apple],3
3,1,1,Chips and Tomatillo-Green Chili Salsa,none,2
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16

In [14]:
df['choice_description']=df['choice_description'].str.replace("["," ")
df['choice_description']=df['choice_description'].str.replace("]"," ")
df.head()

<ipython-input-14-c904a95dbdf5>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df['choice_description'].str.replace("["," ")
<ipython-input-14-c904a95dbdf5>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['choice_description']=df['choice_description'].str.replace("]"," ")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,none,2
1,1,1,Izze,Clementine,3
2,1,1,Nantucket Nectar,Apple,3
3,1,1,Chips and Tomatillo-Green Chili Salsa,none,2
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16

In [15]:
df['choice_description']=df['choice_description'].astype(str)

In [16]:
df.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     6.934660
std     528.890796     0.410186     4.202828
min       1.000000     1.000000     1.000000
25%     477.250000     1.000000     3.000000
50%     926.000000     1.000000     8.000000
75%    1393.000000     1.000000     9.000000
max    1834.000000    15.000000    44.000000

In [17]:
quantity_item=df.groupby('item_name')['quantity'].sum().reset_index(name= 'total_quantity')
quantity_item

                                item_name  total_quantity
0                       6 Pack Soft Drink              55
1                           Barbacoa Bowl              66
2                        Barbacoa Burrito              91
3                   Barbacoa Crispy Tacos              12
4                     Barbacoa Salad Bowl              10
5                     Barbacoa Soft Tacos              25
6                           Bottled Water             211
7                                    Bowl               4
8                                 Burrito               6
9                             Canned Soda             126
10                      Canned Soft Drink             351
11                          Carnitas Bowl              71
12                       Carnitas Burrito              60
13                  Carnitas Crispy Tacos               8
14                         Carnitas Salad               1
15                    Carnitas Salad Bowl               6
16                    Carnitas Soft Tacos              40
17                           Chicken Bowl             761
18                        Chicken Burrito             591
19                   Chicken Crispy Tacos              50
20                          Chicken Salad               9
21                     Chicken Salad Bowl             123
22                     Chicken Soft Tacos             120
23                                  Chips             230
24           Chips and Fresh Tomato Salsa             130
25                    Chips and Guacamole             506
26      Chips and Mild Fresh Tomato Salsa               1
27     Chips and Roasted Chili Corn Salsa              23
28     Chips and Roasted Chili-Corn Salsa              18
29  Chips and Tomatillo Green Chili Salsa              45
30    Chips and Tomatillo Red Chili Salsa              50
31  Chips and Tomatillo-Green Chili Salsa              33
32    Chips and Tomatillo-Red Chili Salsa              25
33                           Crispy Tacos               2
34                                   Izze              20
35                       Nantucket Nectar              29
36                                  Salad               2
37                          Side of Chips             110
38                             Steak Bowl             221
39                          Steak Burrito             386
40                     Steak Crispy Tacos              36
41                            Steak Salad               4
42                       Steak Salad Bowl              31
43                       Steak Soft Tacos              56
44                            Veggie Bowl              87
45                         Veggie Burrito              97
46                    Veggie Crispy Tacos               1
47                           Veggie Salad               6
48                      Veggie Salad Bowl              18
49                      Veggie Soft Tacos               8

In [20]:
most_order=df.sort_values(by="quantity",ascending=False)
most_order.head()

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,none,44
4152,1660,10,Bottled Water,none,15
3887,1559,8,Side of Chips,none,13
3599,1443,7,Bottled Water,none,10
2441,970,5,Bottled Water,none,7

In [24]:
df['total_price']=df['quantity']*df['item_price']
revenue_each=df[df['total_price']!=df['item_price']]
revenue_each

,order_id,quantity,item_name,choice_description,item_price,total_price
4,2,2,Chicken Bowl,"Tomatillo-Red Chili Salsa (Hot), Black Beans...",16,32
18,9,2,Canned Soda,Sprite,2,4
51,23,2,Canned Soda,Mountain Dew,2,4
135,60,2,Chicken Salad Bowl,"Tomatillo Green Chili Salsa, Sour Cream, Che...",22,44
148,67,2,Steak Burrito,"Tomatillo-Red Chili Salsa (Hot), Rice, Chees...",17,34
...,...,...,...,...,...,...
4491,1786,4,Canned Soft Drink,Sprite,5,20
4499,1789,2,Canned Soft Drink,Coke,2,4
4560,1812,2,Canned Soft Drink,Coke,2,4
4561,1813,2,Chicken Salad Bowl,"Fresh Tomato Salsa, Fajita Vegetables, Pinto...",17,34
4582,1822,2,Bottled Water,none,3,6

In [25]:
unique_item =df['item_name'].unique()
unique_item

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)